### ISSUE TITLE
The bot doesn't work

### ISSUE THREAD

**Issue by AriaFantom** [chaseweaver/Ichicode#1]
I try to use the bot when I type a CMD it shows me a error

**Comment by crispyaus** [comment]
Maybe show the error?

**Comment by AriaFantom** [comment]
TypeError: Cannot read property 'antispamMonitor' of undefined
at module.exports.run (/app/monitors/antispam.js:18:29)
    at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
    at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
at module.exports.run (/app/events/message.js:4:57)
    at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
    at KlasaClient.emit (events.js:189:13)
    at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)
[2020-03-03 07:48:01] [MONITOR] /app/monitors/dadjoke.js
[2020-03-03 07:48:01] TypeError: Cannot read property 'dadjokeMonitor' of undefined
[2020-03-03 07:48:01]     at module.exports.run (/app/monitors/dadjoke.js:17:28)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
[2020-03-03 07:48:01]     at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
[2020-03-03 07:48:01]     at module.exports.run (/app/events/message.js:4:57)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-03 07:48:01]     at KlasaClient.emit (events.js:189:13)
[2020-03-03 07:48:01]     at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
[2020-03-03 07:48:01]     at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[2020-03-03 07:48:01]     at WebSocketManager.handlePacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
[2020-03-03 07:48:01]     at WebSocketShard.onPacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)
[2020-03-03 07:48:01] [MONITOR] /app/monitors/iagree.js
[2020-03-03 07:48:01] TypeError: Cannot read property 'iagreeMonitor' of undefined
[2020-03-03 07:48:01]     at module.exports.run (/app/monitors/iagree.js:17:28)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
[2020-03-03 07:48:01]     at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
[2020-03-03 07:48:01]     at module.exports.run (/app/events/message.js:4:57)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-03 07:48:01]     at KlasaClient.emit (events.js:189:13)
[2020-03-03 07:48:01]     at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
[2020-03-03 07:48:01]     at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[2020-03-03 07:48:01]     at WebSocketManager.handlePacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
[2020-03-03 07:48:01]     at WebSocketShard.onPacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)
[2020-03-03 07:48:01] [MONITOR] /app/monitors/logger.js
[2020-03-03 07:48:01] TypeError: Cannot read property 'logger' of undefined
[2020-03-03 07:48:01]     at module.exports.run (/app/monitors/logger.js:17:59)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
[2020-03-03 07:48:01]     at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
[2020-03-03 07:48:01]     at module.exports.run (/app/events/message.js:4:57)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-03 07:48:01]     at KlasaClient.emit (events.js:189:13)
[2020-03-03 07:48:01]     at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
[2020-03-03 07:48:01]     at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[2020-03-03 07:48:01]     at WebSocketManager.handlePacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
[2020-03-03 07:48:01]     at WebSocketShard.onPacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)
[2020-03-03 07:48:01] [MONITOR] /app/monitors/nah.js
[2020-03-03 07:48:01] TypeError: Cannot read property 'nahMonitor' of undefined
[2020-03-03 07:48:01]     at module.exports.run (/app/monitors/nah.js:17:28)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
[2020-03-03 07:48:01]     at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
[2020-03-03 07:48:01]     at module.exports.run (/app/events/message.js:4:57)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-03 07:48:01]     at KlasaClient.emit (events.js:189:13)
[2020-03-03 07:48:01]     at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
[2020-03-03 07:48:01]     at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[2020-03-03 07:48:01]     at WebSocketManager.handlePacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
[2020-03-03 07:48:01]     at WebSocketShard.onPacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)
[2020-03-03 07:48:01] [MONITOR] /app/monitors/rainbow.js
[2020-03-03 07:48:01] TypeError: Cannot read property 'rainbowMonitor' of undefined
[2020-03-03 07:48:01]     at module.exports.run (/app/monitors/rainbow.js:16:75)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
[2020-03-03 07:48:01]     at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
[2020-03-03 07:48:01]     at module.exports.run (/app/events/message.js:4:57)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-03 07:48:01]     at KlasaClient.emit (events.js:189:13)
[2020-03-03 07:48:01]     at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
[2020-03-03 07:48:01]     at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[2020-03-03 07:48:01]     at WebSocketManager.handlePacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
[2020-03-03 07:48:01]     at WebSocketShard.onPacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)
[2020-03-03 07:48:01] [MONITOR] /app/monitors/wakemeup.js
[2020-03-03 07:48:01] TypeError: Cannot read property 'wakemeupMonitor' of undefined
[2020-03-03 07:48:01]     at module.exports.run (/app/monitors/wakemeup.js:17:44)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
[2020-03-03 07:48:01]     at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
[2020-03-03 07:48:01]     at module.exports.run (/app/events/message.js:4:57)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-03 07:48:01]     at KlasaClient.emit (events.js:189:13)
[2020-03-03 07:48:01]     at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
[2020-03-03 07:48:01]     at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[2020-03-03 07:48:01]     at WebSocketManager.handlePacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
[2020-03-03 07:48:01]     at WebSocketShard.onPacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)
[2020-03-03 07:48:01] [MONITOR] /app/monitors/what.js
[2020-03-03 07:48:01] TypeError: Cannot read property 'whatMonitor' of undefined
[2020-03-03 07:48:01]     at module.exports.run (/app/monitors/what.js:17:44)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
[2020-03-03 07:48:01]     at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
[2020-03-03 07:48:01]     at module.exports.run (/app/events/message.js:4:57)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-03 07:48:01]     at KlasaClient.emit (events.js:189:13)
[2020-03-03 07:48:01]     at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
[2020-03-03 07:48:01]     at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[2020-03-03 07:48:01]     at WebSocketManager.handlePacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
[2020-03-03 07:48:01]     at WebSocketShard.onPacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)
[2020-03-03 07:48:01] [MONITOR] /app/monitors/commandHandler.js
[2020-03-03 07:48:01] TypeError: Cannot read property 'disableNaturalPrefix' of undefined
[2020-03-03 07:48:01]     at module.exports.getPrefix (/app/monitors/commandHandler.js:57:24)
[2020-03-03 07:48:01]     at module.exports.parseCommand (/app/monitors/commandHandler.js:46:56)
[2020-03-03 07:48:01]     at module.exports.run (/app/monitors/commandHandler.js:21:50)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
[2020-03-03 07:48:01]     at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
[2020-03-03 07:48:01]     at module.exports.run (/app/events/message.js:4:57)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-03 07:48:01]     at KlasaClient.emit (events.js:189:13)
[2020-03-03 07:48:01]     at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
[2020-03-03 07:48:01]     at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[2020-03-03 07:48:01] [MONITOR] /app/monitors/fuckvulp.js
[2020-03-03 07:48:01] TypeError: Cannot read property 'ctrOneMonitor' of undefined
[2020-03-03 07:48:01]     at module.exports.run (/app/monitors/fuckvulp.js:17:28)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Monitor.js:100:15)
[2020-03-03 07:48:01]     at Map.run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/MonitorStore.js:25:80)
[2020-03-03 07:48:01]     at module.exports.run (/app/events/message.js:4:57)
[2020-03-03 07:48:01]     at module.exports._run (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/dirigeants/klasa/ea059931fad07bdea870620181de453efe816646/node_modules/klasa/src/lib/structures/Event.js:102:15)
[2020-03-03 07:48:01]     at KlasaClient.emit (events.js:189:13)
[2020-03-03 07:48:01]     at MessageCreateAction.handle (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
[2020-03-03 07:48:01]     at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
[2020-03-03 07:48:01]     at WebSocketManager.handlePacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
[2020-03-03 07:48:01]     at WebSocketShard.onPacket (/rbd/pnpm-volume/38a38b23-478a-445b-bdd8-87ce701e9048/node_modules/.github.com/discordjs/discord.js/ecd8cccddf9b83f4f7cd858fdcad9e436ac51794/node_modules/discord.js/src/client/websocket/WebSocketShard.js:437:22)

**Comment by AriaFantom** [comment]
Here is your error

**Comment by Jordaar** [comment]
@Priyanshu348 This bot is outdated I guess.

**Comment by badRyuk** [comment]
@Priyanshu348  Its probably a V11 bot. You may need to update the entire bot code to v12. You will need to view the discordjs guide and documentation to do that
